version: '3.9'
services:
  draft-front:
    build:
      context: .
      # dockerfile: ./Dockerfile.prd
      dockerfile: ./Dockerfile.dev
    # image: yoshi429/draft-react:v-0.0.1
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    tty: true
    working_dir: /app
