version: '3.9'
services:
  draft-front:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - port=3000
      - REACT_APP_BASE_URL=http://localhost
    tty: true
    working_dir: /app
