version: '3.9'
services:
  draft-front:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env
    tty: true
    working_dir: /app
